# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b19e29d8a84af5767f7ab1385f265c564f1f60e5b4408726e2ae16fc823d0036c3e8b7cf0eb8cdfe16edd427f4f03c75ec048f474828ee765d559abd0e83f2d3

test:
  secret_key_base: 28148c42bd49873516929bc237c5a6ded093685dfa930c293b0b4bb4c640e2f50384821f2f213c7fe1ac02fd1a27ddc80e8580b4f706b990089ce22f2fcc4faf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
